#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='vim'
fi
if [[ -z "$VISUAL" ]]; then
  if (( $+commands[gvim] )); then
    export VISUAL='gvim -f'
  else
    export VISUAL='nano'
  fi
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi
export FCEDIT=$EDITOR

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  $HOME/.{cargo,zprezto}/bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Set some ENV variables for apps in Wayland
if [[ ${XDG_SESSION_TYPE} == 'wayland' ]]; then
  # Firefox
  export MOZ_ENABLE_WAYLAND=1
  # VLC
  export QT_QPA_PLATFORM=wayland
  # NixOS
  export NIXOS_OZONE_WL=1
  # Electron Apps
  export ELECTRON_OZONE_PLATFORM_HINT=wayland
fi

if [[ ${XDG_SESSION_TYPE} == 'x11' ]]; then
  # Firefox use native scrolling
  export MOZ_USE_XINPUT2=1
fi

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_ENABLE_HIGHDPI_SCALING=1
