#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Add binaries in zprezto repo to path
path=(
  ${HOME}/.zprezto/bin
  $path
)

# Add binaries in ~/bin to path
if [[ -e ${HOME}/bin ]]; then
  path=(
    ${HOME}/bin
    $path
  )
fi

# Add rust binaries to path
if [[ -e ${HOME}/.cargo/bin ]]; then
  path=(
    ${HOME}/.cargo/bin
    $path
  )
fi

# Debian ack is named ack-grep
if (( $+commands[ack-grep] )); then
  alias ack=ack-grep
fi

# Zsh time is meh
alias time='command time'

# Don't allow npx to install commands
if (( $+commands[npx] )); then
  alias npx="npx --no-install"
fi
