#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Debian ack is named ack-grep
if (( $+commands[ack-grep] )); then
  alias ack=ack-grep
fi

# Zsh time is meh
alias time='command time'

# Initialize nvm
if [[ -e ${HOME}/.nvm ]]; then
  source ${HOME}/.nvm/nvm.sh
fi

# Don't allow npx to install commands
if (( $+commands[npx] )); then
  alias npx="npx --no-install"
fi

# Tmux helpers
if (( $+commands[tmux] )); then
  alias tmuxl="tmux list-sessions"
  function tmuxa {
    local name="${1:-prezto}"
    tmux new-session -A -s "${name}"
  }
fi

# Use doas instead of sudo if installed
if (( $+commands[doas] )); then
  alias sudo="doas"
fi

